apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: mysql
        image: mysql:8.0.27 
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-hostpath
          mountPath: /var/lib/mysql 
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_DATABASE
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_PASSWORD
  volumeClaimTemplates:
  - metadata:
      name: mysql-hostpath 
    spec:
      storageClassName: mysql-hostpath
      accessModes: 
      - ReadWriteMany
      resources:
        requests:
          storage: 1Gi 
