apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:5.8.2-apache
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "500m"
            memory: "500Mi"
          requests:
            cpu: "150m"
            memory: "100Mi" 
        #volumeMounts:
        #- name: wordpress-content
        #  mountPath: /var/www/html/wp-content
        env: 
        - name: WORDPRESS_DB_HOST
          #value: "mysql-service.default.svc.cluster.local:3306"
          value: "mysql-service:3306"
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD  
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE
        # 確保MySQL正確啟動，再來啟動WordPress
        livenessProbe:
          tcpSocket:
            host: mysql-service
            port: 3306
          initialDelaySeconds: 3
          periodSeconds: 600